In [3]:
import dtmapi

# Get all countries for which DTM data is publicly available through the API.
all_country_list = dtmapi.get_all_countries()
all_country_list

                          admin0Name admin0Pcode
0                        Afghanistan         AFG
1                Antigua and Barbuda         ATG
2                      Bahamas (the)         BHS
3                              Benin         BEN
4   Bolivia (Plurinational State of)         BOL
5                       Burkina Faso         BFA
6                            Burundi         BDI
7                           Cameroon         CMR
8           Central African Republic         CAF
9                               Chad         TCD
10  Democratic Republic of the Congo         COD
11                          Djibouti         DJI
12                          Dominica         DMA
13                           Ecuador         ECU
14                       El Salvador         SLV
15                          Ethiopia         ETH
16                              Fiji         FJI
17                           Grenada         GRD
18                         Guatemala         GTM
19                             Haiti         HTI
20                          Honduras         HND
21                         Indonesia         IDN
22                              Iraq         IRQ
23                             Kenya         KEN
24  Lao People's Democratic Republic         LAO
25                           Lebanon         LBN
26                             Libya         LBY
27                        Madagascar         MDG
28                            Malawi         MWI
29                              Mali         MLI
30                          Mongolia         MNG
31                        Mozambique         MOZ
32                             Nepal         NPL
33                             Niger         NER
34                           Nigeria         NGA
35                          Pakistan         PAK
36                  Papua New Guinea         PNG
37                              Peru         PER
38                 Philippines (the)         PHL
39               Republic of Armenia         ARM
40  Saint Vincent and the Grenadines         VCT
41                           Somalia         SOM
42                      South Africa         ZAF
43                       South Sudan         SSD
44                         Sri Lanka         LKA
45                             Sudan         SDN
46                             Syria         SYR
47                            Uganda         UGA
48                           Ukraine         UKR
49                           Vanuatu         VUT
50                             Yemen         YEM
51                            Zambia         ZMB
52                          Zimbabwe         ZWE

In [ ]:
idp_admin0_data = dtmapi.get_idp_admin0_data(CountryName='Somalia', to_pandas=True)

In [21]:
idp_admin0_data

,id,operation,admin0Name,admin0Pcode,numPresentIdpInd,reportingDate,yearReportingDate,monthReportingDate,roundNumber,assessmentType
0,268633,Somalia displacement,Somalia,SOM,430062,2016-06-01T00:00:00,2016,6,1,BA
1,268634,Somalia displacement,Somalia,SOM,149819,2016-07-30T00:00:00,2016,7,2,BA
2,268635,Somalia displacement,Somalia,SOM,346626,2016-10-30T00:00:00,2016,10,3,BA
3,267563,Somalia displacement,Somalia,SOM,90000,2016-12-31T00:00:00,2016,12,4,BA
4,267564,Somalia displacement,Somalia,SOM,237038,2017-01-30T00:00:00,2017,1,5,BA
5,267565,Somalia displacement,Somalia,SOM,293084,2017-02-28T00:00:00,2017,2,6,BA
6,267566,Somalia displacement,Somalia,SOM,675839,2017-03-30T00:00:00,2017,3,7,BA
7,267567,Somalia displacement,Somalia,SOM,806998,2017-04-30T00:00:00,2017,4,8,BA
8,267568,Somalia displacement,Somalia,SOM,850004,2017-05-30T00:00:00,2017,5,9,BA
9,267569,Somalia displacement,Somalia,SOM,874638,2017-06-30T00:00:00,2017,6,10,BA
10,267570,Somalia displacement,Somalia,SOM,944838,2017-07-30T00:00:00,2017,7,11,BA
11,267571,Somalia displacement,Somalia,SOM,1074838,2017-08-30T00:00:00,2017,8,12,BA
12,267572,Somalia displacement,Somalia,SOM,1123838,2017-09-30T00:00:00,2017,9,13,BA
13,267573,Somalia displacement,Somalia,SOM,1155838,2017-10-30T00:00:00,2017,10,14,BA
14,267574,Somalia displacement,Somalia,SOM,1187838,2017-11-30T00:00:00,2017,11,15,BA
15,267979,Somalia - Countrywide Monitoring,Somalia,SOM,1687109,2021-03-30T00:00:00,2021,3,1,BA
16,267980,Somalia - Countrywide Monitoring,Somalia,SOM,4574256,2022-01-31T00:00:00,2022,1,1,BA
17,267981,Somalia - Countrywide Monitoring,Somalia,SOM,3451434,2024-01-31T00:00:00,2024,1,2,BA