In [1]:
import pandas as pd
import seaborn as sns

In [2]:
data = pd.read_csv('data/climate_migration_news.csv')

In [3]:
data_tone = pd.read_csv('data/climate_migration_timelinetone.csv')

In [4]:
#format date column
data['Date'] = pd.to_datetime(data['Date'])

In [5]:
data_somalia = data[data['Country'] == 'Somalia']

In [6]:
data_somalia

,Country,Keyword,Title,URL,Source Country,Date
771,Somalia,drought,FAO inks $43 . 8 million to reduce flood risk ...,https://www.radiodalsan.com/fao-inks-43-8-mill...,Somalia,2023-12-09 08:45:00+00:00
772,Somalia,drought,Devastating Floods Submerge 85 % of Beledweyne...,https://jowhar.com/devastating-floods-submerge...,Somalia,2023-12-08 16:15:00+00:00
773,Somalia,drought,"This Year , Malawi Staple Food , Maize , Could...",https://jowhar.com/this-year-malawis-staple-fo...,Somalia,2024-01-29 15:15:00+00:00
774,Somalia,drought,Garissa Water Future : World Bank supports For...,https://www.radiodalsan.com/garissas-water-fut...,Somalia,2024-01-18 00:30:00+00:00
775,Somalia,drought,Somali National Disaster Agency distributes re...,https://www.radiodalsan.com/somali-national-di...,Somalia,2024-01-04 04:45:00+00:00
...,...,...,...,...,...,...
851,Somalia,drought,"Somaliland : Ports , protests and power projec...",https://somalilandsun.com/ports-protests-and-p...,Somalia,2024-01-18 13:30:00+00:00
852,Somalia,drought,What Somalis are Taking Refuge from – Qaranimo...,https://www.qaranimo.com/2016/01/27/what-somal...,Somalia,2024-02-04 19:45:00+00:00
853,Somalia,drought,"Hunger , terrorism and the threat of war : Som...",https://warsheekh.com/hunger-terrorism-and-the...,Somalia,2024-02-28 18:15:00+00:00
854,Somalia,drought,AISHA AHMED HUSSEIN : ENHANCING ACCESS TO HIGH...,https://wardheernews.com/aisha-ahmed-hussein-e...,Somalia,2024-01-27 15:15:00+00:00
855,Somalia,drought,Which way out for Ethiopia - Somalia impasse ?,https://wardheernews.com/which-way-out-for-eth...,Somalia,2024-01-28 05:15:00+00:00

In [7]:
somalia_mobility = pd.read_excel('data/somalia_mobility_iom_2024.xlsx')

In [8]:
europe_mobility = pd.read_excel('data/DTM_Mixed Migration Flows to Europe_Q3_2024.xlsx',
                                sheet_name='All_Daily Breakdown')

In [9]:
somalia_mobility['date'] = pd.to_datetime(somalia_mobility['Date of Assessment'])

In [12]:
somalia_mobility['month'] = somalia_mobility['date'].dt.month
somalia_mobility[['month','Total new arrivals since last week']].groupby('month').sum()

       Total new arrivals since last week
month
3                                    1744
4                                   21967
5                                   34463
6                                   34682
7                                   47440
8                                   40314
9                                   42759
10                                   7531
11                                   3521
12                                   3537